name: ci

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Install yt-dlp
        run: |
          python3 -m pip install --upgrade pip
          pip install -U yt-dlp

      - name: Download video
        run: |
          git config --local user.email "justjavac@gmail.com"
          git config --local user.name "迷渡"
          git remote set-url origin https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git pull --rebase

          # 使用 yt-dlp + 你原来的 config.txt
          yt-dlp --config-location config.txt

          git add .
          git commit -m "download youtube video" || echo "No changes"
          git push
